# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: nuget
  target-branch: develop
  directory: "/"
  schedule:
    interval: daily
  groups:
    Microsoft:
      patterns:
      - "Microsoft.EntityFrameworkCore"
      - "Microsoft.EntityFrameworkCore.*"
      - "Microsoft.AspNetCore.*"
      - "Microsoft.Extensions.*"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule: 
    interval: daily
  target-branch: develop
